security:
    providers:
      firebase_provider:
          entity:
            class: App\Entity\User
            property: firebaseUid

    firewalls:
        main:
            anonymous: true
            lazy: true
            provider: firebase_provider
            logout: 
                path: /signout
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 1728000
                path: /
            form_login:
                login_path: signin
                check_path: signin
                remember_me: true

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }